### ISSUE TITLE
Nvidia driver detected on non-nvidia system

### ISSUE THREAD

**Issue by t-oster** [openthinclient/os-core#30]
I get a black screen on boot, because the /etx/X11/xorg.conf.d/20-nvidia.conf file is present. I do NOT have an nvidia graphics card.

I suppose the error is in https://github.com/openthinclient/os-core/blob/master/Initrd/init#L308 because the line

   if [ -n "$nvidia" ] && $(lspci | grep -q -i 10DE); then

checks if $nvidia is not empty, but "false" also evaluates to true? I guess I have some hardware containing the 10DE, so this issue may only pop up on some machines which have such hardware by accident.

adding "nvidia=false" to the kernel does not change anything.

If I log in as root after boot (command line), delete the xorg-file and restart lightdm, it works. So the problem is definitely, that this file is created without nvidia gpu present.

**Comment by t-oster** [comment]
Temporary fix:
If I add the command line parameter "nvidia=" without anything else, it works.

**Comment by jfrenzel** [comment]
Hi Thomas, 

thanks for reporting. Luckily this bug is already fixed (i hope so), as i noticed this problem too on some customers installation.

Please update to base version 2.1-12 (manager-testing). In addition, this version one more nvidia driver (304.xx) inside.

Git commit (for version 2.1-12)  will be done today.

Regards, Jörn

**Comment by t-oster** [comment]
looks fine to me in the source, but I don't have time to upgrade right now (never touch a running system). Thanks for the info.
